#!/bin/bash
echo "======================================="
echo "  KN05 Bind Mount Test - Version 2 (UPDATED!)"
echo "  Autor: Ronnilants"
echo "======================================="
echo ""
echo "Hostname des Containers: $(hostname)"
echo "Aktuelles Datum/Uhrzeit: $(date)"
echo "Betriebssystem: $(uname -a)"
echo ""
echo "Meine einzigartige Nachricht:"
echo "  --> Hallo aus dem Bind Mount! Dieses Skript laeuft im Container,"
echo "      aber der Code liegt auf dem Host-System."
echo ""
echo "  --> NEUE ZEILE: Der Host hat dieses Skript veraendert,"
echo "      ohne den Container neu zu starten! Das ist die Magie von Bind Mounts."
